# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65a43a95318784d3072c608bbe4e2e7ff2ea51b357a70132474971cb662615e3765e598cf2dee0b38d84dccb02d54fac2291d107867cf35895a6b86340015081

test:
  secret_key_base: 62c7d9434769a6c8f90918162cc5584799dca58b46d0d2d7cc66b9015b4cb24cb31cec113b84efa096d98b33d70e2d4926003e10a96197b3daab5f31b1f897bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
